server:
  port: 8081
feign:
  client:
    product-service:
      url: "http://localhost:8082"
      connect-timeout: 5000
      read-timeout: 5000
spring:
  application:
    name: orderService
  config:
    import: "optional:configserver:http://localhost:8888"
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    com.cc.orderService: DEBUG
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, busrefresh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

product:
    service:
        baseUrl: http://product-service

resilience4j:
  ratelimiter:
    instances:
      productRateLimiter:
        limit-for-period: 5
        limit-refresh-period: 1s
        timeout-duration: 0
  bulkhead:
    instances:
      productBulkHead:
        maxConcurrentCalls: 2
        maxWaitDuration: 0
  thread-pool-bulkhead:
    instances:
      puoductThreadPoolBulkHead:
        core-thread-pool-size: 1      # threads kept alive normally
        max-thread-pool-size: 2       # max threads it can grow to
        queue-capacity: 1             # requests allowed to wait when all threads busy
        keep-alive-duration: 20ms     # idle time before extra (above core) threads die
  retry:
    instances:
      productRetry:
        max-attempts: 3
        wait-duration: 1s
  circuitbreaker:
    instances:
      productCircuitBreaker:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5      # need 5 calls before it can trip
        failure-rate-threshold: 50      # trip if >=50% fail
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
