spring:
  application:
    name: apigateway
  cloud:                          # 2 spaces -> child of spring
    gateway:
      routes:
        - id: order-service
          uri: lb://orderService
          predicates:
            - Path=/orders/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
#        filters
          filters:
          - name: AddRequestHeader
            args:
              name: X-test-RequestHeader
              value: ApiGatewayRequest
          - name: AddResponseHeader
            args:
              name: X-test-ResponseHeader
              value: ApiGatewayResponse
          - name: RemoveRequestHeader
            args:
              name: Api-private-key
#              Retry
          - name: Retry
            args:
              retries: 4
              methods: GET,DELETE
#Circuit
          - name: CircuitBreaker
            args:
              name: myCircuitBreakerName
              fallbackUri: forward:/fallback

resilience4j:
  circuitbreaker:
    instances:
      myCircuitBreakerName:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30


# Route: Forward /products/** to product service



management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces