spring:
  application:
    name: apigateway
  cloud:                          # 2 spaces -> child of spring
    gateway:
      routes:
        - id: order-service
          uri: lb://orderService
          predicates:
            - Path=/orders/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30


# Route: Forward /products/** to product service
